# Generated by Django 3.2.4 on 2021-08-01 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0013_auto_20210801_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='classlist',
            name='subject_list',
            field=models.ManyToManyField(blank=True, null=True, to='root.Student'),
        ),
    ]
