# Generated by Django 3.2.4 on 2021-08-01 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0014_classlist_subject_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classlist',
            old_name='subject_list',
            new_name='student',
        ),
    ]
