# Generated by Django 3.2.4 on 2021-08-01 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0015_rename_subject_list_classlist_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='uid',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
