# Generated by Django 3.2.4 on 2021-08-02 03:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0017_standard'),
    ]

    operations = [
        migrations.AddField(
            model_name='classlist',
            name='uid',
            field=models.CharField(blank=True, default=uuid.UUID('23619ef0-2c85-4648-8003-752eaceda6a2'), max_length=200),
        ),
    ]
