# Generated by Django 3.2.4 on 2021-08-03 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0022_alter_teacherprofile_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='uid',
        ),
    ]
