# Generated by Django 3.2.4 on 2021-08-03 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0024_teacherprofile_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='uid',
            field=models.CharField(default='98c54793-f81c-4605-9684-8c655b9d8815', max_length=200),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='uid',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
