# Generated by Django 3.2.4 on 2021-08-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0026_alter_teacher_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='uid',
            field=models.CharField(default='54c23015-1a19-42e2-aaff-1a4cfb8884b3', max_length=200),
        ),
    ]
