# Generated by Django 3.2.4 on 2021-08-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0028_alter_teacher_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_uid', models.CharField(blank=True, default='', max_length=100)),
                ('teacher_name', models.CharField(blank=True, default='', max_length=300)),
                ('standard', models.CharField(blank=True, default='', max_length=300)),
                ('class_name', models.CharField(blank=True, default='', max_length=300)),
                ('subject', models.CharField(blank=True, default='', max_length=300)),
                ('student_secret_id', models.CharField(blank=True, default='', max_length=100)),
                ('student_name', models.CharField(blank=True, default='', max_length=300)),
                ('attendance_status', models.CharField(blank=True, default='', max_length=10)),
            ],
        ),
    ]
