# Generated by Django 3.2.4 on 2021-08-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0030_attendancereport_report_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancereport',
            name='submit_time',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
