# Generated by Django 3.2.4 on 2021-08-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0032_auto_20210811_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='uid',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
