# Generated by Django 3.2.4 on 2021-08-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0033_alter_teacher_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='reset_code',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
