# Generated by Django 3.2.4 on 2021-08-13 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0034_teacherprofile_reset_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='house_number',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='student',
            name='parent1',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='student',
            name='parent2',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='student',
            name='relation1',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='student',
            name='relation2',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='student',
            name='telephone1',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='student',
            name='telephone2',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
