# Generated by Django 3.2.6 on 2021-08-20 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0035_auto_20210813_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancereport',
            name='normal_time',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
