# Generated by Django 3.2.6 on 2021-08-20 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0037_rename_submit_time_attendancereport_submit_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancereport',
            old_name='normal_time',
            new_name='normal_date',
        ),
        migrations.RenameField(
            model_name='attendancereport',
            old_name='submit_date',
            new_name='submit_time',
        ),
    ]
