# Generated by Django 3.2.6 on 2021-08-20 05:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0038_auto_20210820_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancereport',
            name='submit_date_field',
            field=models.DateField(blank=True, default=datetime.date(2021, 8, 20)),
        ),
    ]
