# Generated by Django 3.2.6 on 2021-08-20 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0040_attendancereport_xx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancereport',
            name='submit_date_field',
            field=models.DateField(blank=True, default=None),
        ),
    ]
