# Generated by Django 3.2.4 on 2021-08-25 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0043_remove_attendancereport_xx'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='student',
            field=models.ManyToManyField(blank=True, to='root.Student'),
        ),
    ]
