# Generated by Django 3.2.4 on 2021-08-25 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0044_subject_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='student',
        ),
        migrations.CreateModel(
            name='Student_Subject_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.subject')),
            ],
        ),
    ]
